### ISSUE TITLE
[Question] How to make the header sticky?

### ISSUE THREAD

**Issue by taquangtrung** [daviddarnes/alembic#138] opened 2019-10-24 09:52 UTC
Hi,

I'm using your Alembic theme and really love it.

I'd like to ask if it is possible to make the header sticky in your Alembic template?

I saw that the header that Alembic used is not stored in the `<head/>` section but in a section `<header/>` of the `<body/>`. 

Hence, all solutions that I tried online like below don't work

https://css-tricks.com/fixed-headers-on-page-links-and-overlapping-content-oh-my/
https://www.w3schools.com/howto/howto_js_sticky_header.asp

Thank you!

**Comment by daviddarnes** [comment] 2019-10-24 16:17
That's going to require a bit of dev work. Here's what I'd do:
1. Move the feature out of the header component so it sits above the main content area
2. Add the following CSS:
  ``` css
  .header {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    background: white;
  }
  ```

Let us know how it goes. Going to close this as it's not a bug, but happy to chat this through ✨

**Closed by daviddarnes** 2019-10-24 16:17 UTC
Labels: help wanted, question

**Comment by taquangtrung** [comment] 2019-10-25 02:27
@daviddarnes : excellent! I think the key point here is to set `background: white;`. I didn't set it previously, hence when scrolling the content could go to the top of the page.

I also need to put `margin-top: 5rem;` insider `.feature` to push the feature image down below the header when the page is first loaded. My `.feature` setting is like below:

```
.feature {
  padding-bottom: .4rem;
  margin-bottom: 1.6rem;
  text-align: center;
  background: $featureBackgroundColour;
  background-size: cover;
  background-position: center;
  min-height: 200px;
  .container {
    min-height: 35vh;
    max-width: 60%;
    @include flex-direction(column);
    @include justify-content(center);
  }

  @media screen and (min-width: 10px) {
      margin-top: 0rem;
  }

  @media screen and (min-width: 800px) {
      margin-top: 5rem;
  }
}
```

**Comment by taquangtrung** [comment] 2019-10-25 02:55
I have a new question. Is this possible to change the background color of the header when the webpage is scrolled?

That is, initially, the header is white. But when the image feature is scrolled and disappear, can I change the background color to dark green like the footer?

**Comment by taquangtrung** [comment] 2019-10-25 13:17
I finally can change the header's background color by adding the following code to the fiel `site-header.html`:

```
<script type="text/javascript">
 window.onscroll = () => {
   const header = document.querySelector('header');
   if(this.scrollY <= 150) header.className = 'header';
   else header.className = 'header scroll';
 };
</script>
```

and using this code in the file `_theme.scss`

```
// sticky header
.header {
  position: fixed;
  width: 100%;
  background: white;
}

// sticky header, change color when scrolling
.header.scroll {
    position: fixed;
    width: 100%;
    background: #e4efee;
}
```

**Comment by taquangtrung** [comment] 2019-10-25 14:04
I decided to not change the background color, but draw a bottom line in the header, which look nicer. Here is my code:

```
.header.scroll {
    position: fixed;
    width: 100%;
    background: white;
    border-bottom: 1px solid $linkColour;
}
```

Also, I change all ordered lists to unordered lists, to avoid the bug that displays the indexing numbers on top of the sticky header. (But this bug still happens with ordered list).

**Comment by daviddarnes** [comment] 2019-10-25 15:54
I really liked this thread of you working it all out piece by piece. You should totally write this up in a blog post! 💚

**Comment by taquangtrung** [comment] 2019-10-26 02:13
Thanks a lot for your help and suggestion. I will try to write a blog post soon. :-)
